Repository Eagle2gle/wealth-marble-frontend, pull requests merged in 2023-01, with the labels that each got.

#2 chore: Redux 설치
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/pages/counter.tsx
  src/store/index.ts
  src/store/modules/counter.ts
  src/store/modules/index.ts
Labels: :package: chore

#5 [chore] Eslint가 제대로 작동하지 않는 문제 해결
  .eslintrc.json
  package-lock.json
Labels: :package: chore

#10 [style] 로그인 페이지 UI 구현
  src/components/SocialLoginBtn.tsx
  src/components/common/Icons.tsx
  src/pages/login.tsx
Labels: :art: style

#12 fix: 헤더 배경 추가
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/pages/_app.tsx
  src/utils/classnames.ts
Labels: :hammer_and_pick: fix

#14 [style] 공모 목록 페이지 UI
  package-lock.json
  package.json
  public/cahootListData.json
  public/cahootRecapData.json
  public/deadlineBannerData.json
  public/deadlineCarouselData.json
  src/components/CahootList.tsx
  src/components/CahootRecap.tsx
  src/components/DeadlineBanner.tsx
  src/components/DeadlineCarousel.tsx
  src/components/common/Carousel.tsx
  src/components/common/Header.tsx
  src/components/common/Icons.tsx
  src/components/common/Search.tsx
  src/pages/_app.tsx
  src/pages/cahoots.tsx
  tailwind.config.js
Labels: :art: style, :hammer_and_pick: fix, :recycle: refactor

#17 [refactor] Redux 코드 업데이트
  src/pages/_app.tsx
  src/pages/counter.tsx
  src/store/index.ts
  src/store/modules/counter.ts
  src/store/modules/index.ts
Labels: :recycle: refactor

#18 [style] 공모 생성 페이지 UI 구현
  package-lock.json
  package.json
  src/components/PlaceSearchBar.tsx
  src/components/common/DateRangeInput.tsx
  src/components/common/FormItem.tsx
  src/components/common/Header.tsx
  src/components/common/Icons.tsx
  src/components/common/ImageUpload.tsx
  src/components/common/Layout.tsx
  src/components/common/NumberInput.tsx
  src/components/common/RadioBtn.tsx
  src/components/common/TextArea.tsx
  src/components/common/TextInput.tsx
  src/pages/cahoots/create.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: :art: style, :sparkles: feat

#21 [fix] 헤더가 정상적으로 나오지 않는 문제 해결
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
Labels: :bug: bug
