Repository Eagle2gle/wealth-marble-frontend, pull requests merged in 2023-03, with the labels that each got.

#71 [feat] 구글 소셜 로그인 구현
  .env
  package-lock.json
  package.json
  src/components/SocialLoginBtn.tsx
  src/pages/_app.tsx
  src/pages/oauth2/redirect.tsx
  src/store/index.ts
  src/store/modules/index.ts
  src/store/modules/user.ts
Labels: :package: chore, :sparkles: feat, :hammer_and_pick: fix, :recycle: refactor

#73 [feat] 관심(북마크) 기능
  package-lock.json
  package.json
  src/components/cahoot/DetailBody.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/InterestButton.tsx
  src/components/cahoot/List.tsx
  src/components/cahoot/ListItems.tsx
  src/components/common/Header.tsx
  src/components/common/InterestButton.tsx
  src/components/common/Interests.tsx
  src/components/market/Interests.tsx
  src/components/market/List.tsx
  src/libs/client/api.ts
  src/pages/_app.tsx
  src/pages/cahoots/create.tsx
  src/pages/cahoots/detail/[id].tsx
  src/pages/cahoots/index.tsx
  src/pages/index.tsx
  src/pages/markets/index.tsx
  src/pages/oauth2/redirect.tsx
  src/store/index.ts
  src/store/modules/index.ts
  src/types/response.d.ts
  tailwind.config.js
Labels: :package: chore, :sparkles: feat, :hammer_and_pick: fix, :recycle: refactor

#76 [feat] 마켓 검색
  src/components/cahoot/List.tsx
  src/components/market/List.tsx
  src/components/market/ListItems.tsx
  src/constants/market.ts
  src/pages/_app.tsx
  src/pages/cahoots/index.tsx
  src/pages/markets/index.tsx
  src/types/market.d.ts
Labels: :sparkles: feat

#75 [style] 마이페이지 레이아웃 작업
  src/components/common/Icons.tsx
  src/components/common/Table.tsx
  src/components/mypage/ParticipatedContest.tsx
  src/components/mypage/Stocks.tsx
  src/components/mypage/Transactions.tsx
  src/components/mypage/UserInfo.tsx
  src/pages/mypage/cahoots.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/management.tsx
  src/pages/mypage/stocks.tsx
  src/pages/mypage/transactions.tsx
  tailwind.config.js
Labels: :art: style

#77 [style] 마이페이지 레이아웃 추가 작업
  src/components/mypage/UserInfo.tsx
Labels: :art: style

#82 [feat] 마이페이지 API 연동
  src/components/common/RouteGuard.tsx
  src/components/common/Table.tsx
  src/components/mypage/ContestTable.tsx
  src/components/mypage/ParticipatedContest.tsx
  src/components/mypage/StockTable.tsx
  src/components/mypage/Stocks.tsx
  src/components/mypage/TransactionTable.tsx
  src/components/mypage/Transactions.tsx
  src/components/mypage/UserInfo.tsx
  src/components/mypage/UserInfoManagement.tsx
  src/constants/mypage.ts
  src/pages/mypage/cahoots.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/management.tsx
  src/pages/mypage/stocks.tsx
  src/pages/mypage/transactions.tsx
  src/types/user.d.ts
Labels: :sparkles: feat

#84 [bug] user 상태 관련 오류
  src/store/modules/user.ts
Labels: :hammer_and_pick: fix

#91 [bug] 이미지 remotePatterns 오류
  next.config.js
Labels: :hammer_and_pick: fix

#92 [bug] 당일 마감 공모에 대한 표시 버그
  src/components/cahoot/DeadlineCarousel.tsx
  src/utils/date.ts
Labels: :hammer_and_pick: fix

#93 [feat] 마켓 페이지 - 가격 정보 API 연동
  src/components/market/PriceInfo.tsx
  src/components/market/PriceInfoItem.tsx
  src/components/market/PriceInfoUpdate.tsx
  src/types/market.d.ts
Labels: :sparkles: feat

#96 [docs] 기술스택 아이콘 추가
  README.md
Labels: 🖍 docs

#97 [feat] 뒤로가기 구현
  src/components/common/GoBackButton.tsx
  src/components/mypage/HeaderWithBackButton.tsx
  src/pages/cahoots/create.tsx
  src/pages/mypage/cahoots.tsx
  src/pages/mypage/management.tsx
  src/pages/mypage/stocks.tsx
  src/pages/mypage/transactions.tsx
Labels: :sparkles: feat

#98 [style] 썸네일 이미지 변경
  public/images/thumbnail.jpeg
  src/components/Thumbnail.tsx
Labels: :art: style

#100 [feat] 메인페이지 API 연동
  src/components/RecentUploadCarousel.tsx
  src/components/RecommendedList.tsx
  src/components/TopFiveList.tsx
  src/components/common/ButtonGroup.tsx
  src/components/common/InterestButton.tsx
  src/components/common/SelectBox.tsx
  src/pages/cahoots/create.tsx
  src/types/cahoot.d.ts
  src/types/market.d.ts
Labels: :art: style, :sparkles: feat

#102 [feat] 마켓 거래
  .env
  package-lock.json
  package.json
  src/components/market/DetailBody.tsx
  src/components/market/OrderBook.tsx
  src/components/market/OrderInput.tsx
  src/components/market/TradeTab.tsx
  src/hooks/useStomp.ts
  src/pages/markets/detail/[id].tsx
  src/pages/markets/index.tsx
  src/store/modules/index.ts
  src/store/modules/marketOrder.ts
  src/types/market.d.ts
  src/utils/date.ts
Labels: :package: chore, :sparkles: feat, :hammer_and_pick: fix

#112 [release] 핫픽스 배포
  src/components/cahoot/BuyButton.tsx
Labels: :fire: hotfix

#117 [release] 핫픽스 배포
  src/components/cahoot/DeadlineCarousel.tsx
  src/components/common/Search.tsx
Labels: :fire: hotfix
