Repository Eagle2gle/wealth-marble-frontend, pull requests merged in 2023-04, with the labels that each got.

#123 [fix] 마켓 가격 정보 소수점 처리
  src/components/market/PriceInfoItem.tsx
Labels: :hammer_and_pick: fix

#127 [feat] SSR 적용
  .eslintrc.json
  src/components/RecentUploadCarousel.tsx
  src/components/RecommendedList.tsx
  src/components/TopFiveList.tsx
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/DeadlineBanner.tsx
  src/components/cahoot/DeadlineCarousel.tsx
  src/components/cahoot/DetailBody.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/DetailStatus.tsx
  src/components/cahoot/List.tsx
  src/components/cahoot/OrderMobile.tsx
  src/components/cahoot/Recap.tsx
  src/components/common/ErrorFallback.tsx
  src/components/common/InterestButton.tsx
  src/components/common/Interests.tsx
  src/components/common/Interests/Carousel.tsx
  src/components/common/Interests/Skeleton.tsx
  src/components/common/Interests/index.tsx
  src/components/common/Interests/types.d.ts
  src/components/common/SearchList/CahootItems.tsx
  src/components/common/SearchList/MarketItems.tsx
  src/components/common/SearchList/Skeleton.tsx
  src/components/common/SearchList/index.tsx
  src/components/common/SearchList/type.d.ts
  src/components/common/SelectBox.tsx
  src/components/home/RecentUploadCarousel.tsx
  src/components/home/RecommendedList/Items.tsx
  src/components/home/RecommendedList/RecommededSelectBox.tsx
  src/components/home/RecommendedList/Skeleton.tsx
  src/components/home/RecommendedList/index.tsx
  src/components/home/TopFiveList/Items.tsx
  src/components/home/TopFiveList/Skeleton.tsx
  src/components/home/TopFiveList/index.tsx
  src/components/market/DetailBody.tsx
  src/components/market/DetailHeader.tsx
  src/components/market/OrderBook.tsx
  src/components/market/PriceInfo/Item.tsx
  src/components/market/PriceInfo/Skeleton.tsx
  src/components/market/PriceInfo/Update.tsx
  src/components/market/PriceInfo/index.tsx
  src/components/market/TradeTab.tsx
  src/components/mypage/ParticipatedContest.tsx
  src/components/mypage/Stocks.tsx
  src/components/mypage/Transactions.tsx
  src/pages/cahoots/create.tsx
  src/pages/cahoots/detail/[id].tsx
  src/pages/cahoots/index.tsx
  src/pages/index.tsx
  src/pages/markets/detail/[id].tsx
  src/pages/markets/index.tsx
  src/pages/mypage/cahoots.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/management.tsx
  src/pages/mypage/stocks.tsx
  src/pages/mypage/transactions.tsx
  src/types/response.d.ts
  src/utils/classnames.ts
Labels: :sparkles: feat

#131 [feat] 마켓 상세 페이지 시세, 정보 탭 구현
  package-lock.json
  package.json
  src/components/market/DetailBody.tsx
  src/components/market/DetailInfo.tsx
  src/components/market/DetailStatus.tsx
  src/types/market.d.ts
  src/utils/date.ts
Labels: :sparkles: feat

#132 [fix] 나라 목록 API 요청 여러번 하는 버그 수정
  src/components/cahoot/CountrySelectBox.tsx
  src/pages/cahoots/create.tsx
Labels: :hammer_and_pick: fix

#128 [refactor] Query key 개선
  package-lock.json
  package.json
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/CountrySelectBox.tsx
  src/components/cahoot/DeadlineBanner.tsx
  src/components/cahoot/DeadlineCarousel.tsx
  src/components/cahoot/DetailBody.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/DetailStatus.tsx
  src/components/cahoot/OrderMobile.tsx
  src/components/cahoot/Recap.tsx
  src/components/common/ButtonGroup.tsx
  src/components/common/InterestButton.tsx
  src/components/common/Interests/Carousel.tsx
  src/components/common/SearchList/CahootItems.tsx
  src/components/common/SearchList/MarketItems.tsx
  src/components/home/RecentUploadCarousel.tsx
  src/components/home/RecommendedList/Items.tsx
  src/components/home/RecommendedList/RecommededSelectBox.tsx
  src/components/home/TopFiveList/Items.tsx
  src/components/home/TopFiveList/constants.ts
  src/components/home/TopFiveList/index.tsx
  src/components/home/TopFiveList/types.d.ts
  src/components/market/DetailBody.tsx
  src/components/market/DetailHeader.tsx
  src/components/market/DetailInfo.tsx
  src/components/market/DetailStatus.tsx
  src/components/market/OrderBook.tsx
  src/components/market/OrderInput.tsx
  src/components/market/PriceInfo/Item.tsx
  src/components/market/TradeTab.tsx
  src/components/mypage/ContestTable.tsx
  src/components/mypage/StockTable.tsx
  src/components/mypage/TransactionTable.tsx
  src/components/mypage/UserInfo.tsx
  src/components/mypage/UserInfoManagement.tsx
  src/pages/cahoots/detail/[id].tsx
  src/pages/cahoots/index.tsx
  src/pages/index.tsx
  src/pages/markets/detail/[id].tsx
  src/pages/markets/index.tsx
  src/pages/mypage/cahoots.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/management.tsx
  src/pages/mypage/stocks.tsx
  src/pages/mypage/transactions.tsx
  src/queries/cahoots.ts
  src/queries/index.ts
  src/queries/interests.ts
  src/queries/markets.ts
  src/queries/users.ts
Labels: :package: chore, :recycle: refactor

#130 [refactor] per-page layout 적용
  src/pages/_app.tsx
  src/pages/cahoots/detail/[id].tsx
  src/pages/cahoots/index.tsx
  src/pages/index.tsx
  src/pages/markets/detail/[id].tsx
  src/pages/markets/index.tsx
  src/pages/mypage/index.tsx
Labels: :sparkles: feat, :recycle: refactor

#134 [refactor] 관심상품 optimistic update 적용
  package-lock.json
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/DetailBody.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/DetailStatus.tsx
  src/components/cahoot/OrderMobile.tsx
  src/components/common/InterestButton.tsx
  src/components/common/SearchList/CahootItems.tsx
  src/components/common/SearchList/index.tsx
  src/components/home/RecommendedList/Items.tsx
  src/pages/_app.tsx
  src/pages/cahoots/detail/[id].tsx
  src/pages/cahoots/index.tsx
  src/pages/index.tsx
  src/pages/markets/detail/[id].tsx
  src/pages/markets/index.tsx
  src/pages/mypage/cahoots.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/stocks.tsx
  src/pages/mypage/transactions.tsx
  src/queries/cahoots.ts
  src/store/modules/cahoot/search.ts
  src/store/modules/index.ts
Labels: :package: chore, :sparkles: feat, :recycle: refactor

#136 [release] v0.2.4 배포
  package-lock.json
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/DetailBody.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/DetailStatus.tsx
  src/components/cahoot/OrderMobile.tsx
  src/components/common/InterestButton.tsx
  src/components/common/SearchList/CahootItems.tsx
  src/components/common/SearchList/index.tsx
  src/components/home/RecommendedList/Items.tsx
  src/pages/_app.tsx
  src/pages/cahoots/detail/[id].tsx
  src/pages/cahoots/index.tsx
  src/pages/index.tsx
  src/pages/markets/detail/[id].tsx
  src/pages/markets/index.tsx
  src/pages/mypage/cahoots.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/stocks.tsx
  src/pages/mypage/transactions.tsx
  src/queries/cahoots.ts
  src/store/modules/cahoot/search.ts
  src/store/modules/index.ts
Labels: :rocket: release

#137 [fix] Image 태그 blur 관련 속성 제거
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/market/DetailHeader.tsx
  src/components/market/DetailInfo.tsx
  src/components/market/TradeTab.tsx
Labels: :hammer_and_pick: fix
