Repository Eagle2gle/wealth-marble-frontend, pull requests merged in 2023-02, with the labels that each got.

#22 [style] 공모 상세 페이지 UI
  .eslintignore
  next.config.js
  package-lock.json
  package.json
  public/cahootDetailData.json
  public/cahootHistoryData.json
  src/components/CahootList.tsx
  src/components/DeadlineBanner.tsx
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/DeadlineBanner.tsx
  src/components/cahoot/DeadlineCarousel.tsx
  src/components/cahoot/DetailBody.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/DetailStatus.tsx
  src/components/cahoot/List.tsx
  src/components/cahoot/Order.tsx
  src/components/cahoot/OrderMobile.tsx
  src/components/cahoot/QuantityButtons.tsx
  src/components/cahoot/QuantityInput.tsx
  src/components/cahoot/Recap.tsx
  src/components/common/BottomBar.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Carousel.tsx
  src/components/common/Icons.tsx
  src/components/common/Modal.tsx
  src/components/common/TabButton.tsx
  src/constants/cahoot.ts
  src/hooks/useSuspendedQuery.ts
  src/libs/client/fetcher.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/cahoots.tsx
  src/pages/cahoots/detail/[id].tsx
  src/pages/cahoots/index.tsx
  src/pages/counter.tsx
  src/store/index.ts
  src/store/modules/cahootOrder.ts
  src/store/modules/counter.ts
  src/store/modules/index.ts
  src/styles/globals.css
  src/types/response.d.ts
  src/utils/dateFormat.ts
  tailwind.config.js
Labels: :package: chore, :art: style, :sparkles: feat, :hammer_and_pick: fix

#24 [style] 홈페이지 UI 구현
  public/RecentUploadCarouselData.json
  public/images/thumbnail.jpeg
  src/components/RecentUploadCarousel.tsx
  src/components/RecommendedList.tsx
  src/components/Thumbnail.tsx
  src/components/TopFiveList.tsx
  src/components/common/Icons.tsx
  src/components/common/SelectBox.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: :art: style

#25 [feat] 공모 관련 API 연동
  next.config.js
  public/cahootDetailData.json
  public/cahootHistoryData.json
  public/cahootListData.json
  public/cahootRecapData.json
  public/deadlineBannerData.json
  public/deadlineCarouselData.json
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/DeadlineBanner.tsx
  src/components/cahoot/DeadlineCarousel.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/DetailStatus.tsx
  src/components/cahoot/List.tsx
  src/components/cahoot/OrderMobile.tsx
  src/components/cahoot/Recap.tsx
  src/components/common/Search.tsx
  src/libs/client/fetcher.ts
  src/pages/cahoots/detail/[id].tsx
  src/types/cahoot.d.ts
  src/types/response.d.ts
Labels: :package: chore, :sparkles: feat

#29 [fix] 웹팩 관련 빌드 에러 해결
  public/cahootListData.json
  src/components/TopFiveList.tsx
  src/pages/cahoots/index.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: :hammer_and_pick: fix

#32 [chore] Oracle Cloud 배포
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  package-lock.json
  package.json
Labels: :package: chore

#34 [feat] 공모 목록 무한 스크롤
  src/components/cahoot/List.tsx
  src/components/cahoot/ListItems.tsx
  src/pages/api/mock/infinite-cahoot.ts
  src/pages/cahoots/index.tsx
Labels: :sparkles: feat, :recycle: refactor

#36 [release] 1차 배포 수정
  .github/workflows/CD.yml
Labels: :rocket: release, :fire: hotfix

#43 [fix] 공모 상세 페이지 수정
  .github/workflows/CI.yml
  next.config.js
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/OrderMobile.tsx
  src/pages/api/mock/infinite-cahoot.ts
  src/types/cahoot.d.ts
Labels: :package: chore, :hammer_and_pick: fix

#45 [bug] 메인 페이지 hydration 오류
  src/pages/index.tsx
Labels: :hammer_and_pick: fix

#49 [style] 마켓 목록 페이지 - 최근 거래 휴양지
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/ListItems.tsx
  src/components/cahoot/Recap.tsx
  src/components/market/RecentTrade.tsx
  src/pages/api/mock/markets/recents.ts
  src/pages/markets/index.tsx
  src/utils/date.ts
  src/utils/dateFormat.ts
  tailwind.config.js
Labels: :art: style, :sparkles: feat, :recycle: refactor

#50 [style] 장소별 추천 휴양지 필터링 UI 구현
  src/components/RecommendedList.tsx
  src/components/common/ButtonGroup.tsx
  src/components/common/Icons.tsx
  src/components/common/SelectBox.tsx
Labels: :art: style

#48 [style] 마켓 목록 페이지 - 관심가는 휴양지
  .eslintrc.json
  package-lock.json
  package.json
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/ListItems.tsx
  src/components/cahoot/Recap.tsx
  src/components/common/Icons.tsx
  src/components/market/Interests.tsx
  src/components/market/RecentTrade.tsx
  src/pages/api/mock/markets/interests.ts
  src/pages/api/mock/markets/recents.ts
  src/pages/markets/index.tsx
  src/utils/date.ts
  src/utils/dateFormat.ts
  tailwind.config.js
Labels: :package: chore, :art: style, :sparkles: feat

#59 [style] 마켓 목록 페이지 - 마켓 목록 아이템
  src/components/market/Interests.tsx
  src/components/market/List.tsx
  src/components/market/ListItems.tsx
  src/pages/api/mock/markets/index.ts
  src/pages/markets/index.tsx
Labels: :art: style

#60 [style] 마켓 페이지 - 가격 정보
  src/components/common/Icons.tsx
  src/components/market/PriceInfo.tsx
  src/components/market/PriceInfoItem.tsx
  src/components/market/PriceInfoUpdate.tsx
  src/pages/api/mock/markets/price.ts
  src/pages/markets/index.tsx
  src/utils/date.ts
Labels: :art: style, :sparkles: feat

#61 [feat] 오늘 마감 임박 슬라이드 애니메이션
  src/components/cahoot/DeadlineBanner.tsx
  src/pages/api/mock/cahoots/mini.ts
  src/types/cahoot.d.ts
Labels: :sparkles: feat

#63 [fix] 공모 검색 API 변경사항 반영
  src/components/cahoot/BuyButton.tsx
  src/components/cahoot/DeadlineCarousel.tsx
  src/components/cahoot/DetailHeader.tsx
  src/components/cahoot/DetailInfo.tsx
  src/components/cahoot/InterestButton.tsx
  src/components/cahoot/ListItems.tsx
  src/components/cahoot/Recap.tsx
  src/pages/api/mock/infinite-cahoot.ts
  src/pages/cahoots/detail/[id].tsx
  src/types/cahoot.d.ts
Labels: :sparkles: feat, :hammer_and_pick: fix

#62 [feat] 공모 생성 페이지
  package-lock.json
  package.json
  src/components/PlaceSearchBar.tsx
  src/components/RecommendedList.tsx
  src/components/common/DateRangeInput.tsx
  src/components/common/Icons.tsx
  src/components/common/ImageUpload.tsx
  src/components/common/NumberInput.tsx
  src/components/common/SelectBox.tsx
  src/components/common/TextArea.tsx
  src/components/common/TextInput.tsx
  src/pages/cahoots/create.tsx
Labels: :sparkles: feat
